---
- name: Recreate kube-dns
  ansible.builtin.command: kubectl --kubeconfig={{ kubeadmin_config }} -n kube-system delete pods -l k8s-app=kube-dns
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
