apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: tracee
    meta.helm.sh/release-namespace: tracee
  creationTimestamp: "2024-01-24T16:41:02Z"
  generation: 1
  labels:
    app: tracee-operator
    pod-template-hash: 7494646f7
  name: tracee-operator-7494646f7
  namespace: tracee
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: tracee-operator
    uid: c6e0e8ef-2a20-4eb5-9b31-42256fe44605
  resourceVersion: "280120"
  uid: 29e01394-de65-457d-aedf-e7d2315f7bd8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracee-operator
      pod-template-hash: 7494646f7
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tracee-operator
        pod-template-hash: 7494646f7
    spec:
      containers:
      - args:
        - --health-probe-bind-address
        - :8081
        command:
        - /tracee/tracee-operator
        env:
        - name: TRACEE_NAME
          value: tracee
        - name: TRACEE_NAMESPACE
          value: tracee
        image: docker.io/aquasec/tracee:0.19.0
        imagePullPolicy: IfNotPresent
        name: tracee-operator
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tracee-operator
      serviceAccountName: tracee-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
